plugins:
  - jekyll-seo-tag
  
collections:
  projects:
    output: true

social:
  name: AVX
  links:
    - https://www.facebook.com/a510ru
    - https://www.instagram.com/a510ru

logo: /images/logo.png
url: https://avx.notstupid.name

title: ""
lang: "ru_RU"

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/logo.png
